@echo When you continue you will see the first test run ...
@pause
python solve_quadratics.py
@echo When you continue you will see the second test run ...
@pause
python solve_quadratics.py 1
@echo When you continue you will see the third test run ...
@pause
python solve_quadratics.py 1 2
@echo When you continue you will see the fourth test run ...
@pause
python solve_quadratics.py 1 2 3 4
@echo When you continue you will see the fifth test run ...
python solve_quadratics.py 1 2 3
@echo When you continue you will see the sixth test run ...
python solve_quadratics.py 2 3 4
@echo When you continue you will see the seveth test run ...
python solve_quadratics.py 1 1 3
@echo When you continue you will see the eigth test run ...
python solve_quadratics.py 2 7 -3
@echo When you continue you will see the ninth test run ...
python solve_quadratics.py 2 -7 3
@echo When you continue you will see the tenth test run ...
python solve_quadratics.py 1 0 1
@echo When you continue you will see the eleventh test run ...
python solve_quadratics.py 1 -1 0
@echo When you continue you will see the twelfth test run ...
python solve_quadratics.py 1 -2 1
@echo When you continue this batch file of test runs will terminate ...
@pause
